# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Masonry'
pod 'SnapKit'

target 'ChangeFontSizeTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChangeFontSizeTest

end
